# Generated by Django 2.0.3 on 2018-03-12 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='网站标题')),
            ],
            options={
                'verbose_name': '网站标题',
                'verbose_name_plural': '网站标题',
                'db_table': 'tb_title',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('user_passwd', models.CharField(max_length=100, verbose_name='密码')),
                ('user_name', models.CharField(default='管理员', max_length=20, verbose_name='用户名')),
                ('user_gender', models.CharField(choices=[('F', '女'), ('M', '男')], default='F', max_length=4)),
                ('user_age', models.SmallIntegerField(verbose_name='年龄')),
                ('user_avatar', models.ImageField(default='static/userimgs/default_avatar.jpg', upload_to='static/userimgs', verbose_name='用户头像')),
                ('user_createdat', models.DateTimeField(default=datetime.datetime(2018, 3, 12, 9, 33, 2, 549642), verbose_name='注册时间')),
                ('user_updatedat', models.DateTimeField(default=datetime.datetime(2018, 3, 12, 9, 33, 2, 549642), verbose_name='更新时间')),
                ('user_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
            options={
                'verbose_name': '用户列表',
                'verbose_name_plural': '用户列表',
                'db_table': 'tb_users',
            },
        ),
    ]
