# Generated by Django 2.0.3 on 2018-03-12 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='logo',
            field=models.ImageField(null=True, upload_to='static/logoimgs', verbose_name='企业logo'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_createdat',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 12, 13, 54, 57, 526484), verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_updatedat',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 12, 13, 54, 57, 526484), verbose_name='更新时间'),
        ),
    ]
