# Generated by Django 2.0.3 on 2018-03-13 04:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180312_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectype_name', models.CharField(max_length=20, verbose_name='二级分类')),
            ],
            options={
                'verbose_name': '二级分类',
                'verbose_name_plural': '二级分类',
                'db_table': 'tb_sectype',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, verbose_name='导航分类')),
            ],
            options={
                'verbose_name': '导航分类',
                'verbose_name_plural': '导航分类',
                'db_table': 'tb_types',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='user_createdat',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 13, 12, 42, 33, 910009), verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_updatedat',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 13, 12, 42, 33, 910009), verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='sectypes',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Types', verbose_name='导航分类'),
        ),
    ]
